// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBastan0fq6lvOsD8lAUqhGcztvP8LE6bo',
    appId: '1:550822266542:web:1879d9b3e5e8771f8bcf3f',
    messagingSenderId: '550822266542',
    projectId: 'babyshophub-fc801',
    authDomain: 'babyshophub-fc801.firebaseapp.com',
    databaseURL: 'https://babyshophub-fc801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babyshophub-fc801.firebasestorage.app',
    measurementId: 'G-EKZ85C2X8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlf1dpkBVWDHxJVIuny32SH1Eyod3cW1Y',
    appId: '1:550822266542:android:c86048eb5d3096558bcf3f',
    messagingSenderId: '550822266542',
    projectId: 'babyshophub-fc801',
    databaseURL: 'https://babyshophub-fc801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babyshophub-fc801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45hp9qVQ4AuY-81JZfcv-t_hufwOsnHk',
    appId: '1:550822266542:ios:bc1a35700fb5f1ca8bcf3f',
    messagingSenderId: '550822266542',
    projectId: 'babyshophub-fc801',
    databaseURL: 'https://babyshophub-fc801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babyshophub-fc801.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45hp9qVQ4AuY-81JZfcv-t_hufwOsnHk',
    appId: '1:550822266542:ios:bc1a35700fb5f1ca8bcf3f',
    messagingSenderId: '550822266542',
    projectId: 'babyshophub-fc801',
    databaseURL: 'https://babyshophub-fc801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babyshophub-fc801.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBastan0fq6lvOsD8lAUqhGcztvP8LE6bo',
    appId: '1:550822266542:web:4b490a02cf8be7978bcf3f',
    messagingSenderId: '550822266542',
    projectId: 'babyshophub-fc801',
    authDomain: 'babyshophub-fc801.firebaseapp.com',
    databaseURL: 'https://babyshophub-fc801-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'babyshophub-fc801.firebasestorage.app',
    measurementId: 'G-46GMNE47BK',
  );

}